carob-data/carob

references/doi_10.21421_D2_AVKD0T.ris
references/doi_10.21421_D2_FATVHT.ris
scripts/fertilizer/doi_10.21421_D2_AVKD0T.R
scripts/fertilizer/doi_10.21421_D2_FATVHT.R

add doi:10.21421/D2/AVKD0T & doi:10.21421/D2/FATVHT

---

scripts/fertilizer/doi_10.25502_07RT-7A40_D.R

Maize response to N and P [Data set]

Maize response to N and P [Data set]

---

scripts/fertilizer/doi_10.7910_DVN_OF7M9D.R
scripts/fertilizer/doi_10.7910_DVN_RKUMXB.R
scripts/fertilizer/doi_10.7910_DVN_UNLRGC.R
scripts/variety_performance/doi_10.7910_DVN_OF7M9D.R

Fixing several scripts with license cahnges or corrections

License fixes

---

scripts/variety_performance/doi_10.25502_2788-9J45.R
terms/crops.csv

Adding scripts/variety_performance/doi_10.25502_6G5B-RM44_D.R and modified crops.csv by adding soy_bean

Adding scripts/variety_performance/doi_10.25502_6G5B-RM44_D.R and modified crops.csv

---

terms/records.csv

Additions in the definitions  of region, adm1, adm2 and adm3  in /carob/terms/records

 definitions in /carob/terms/records

---

scripts/variety_performance/doi_10.25502_hwdb-p578.R
scripts/variety_performance/doi_10.25502_q4wa-ap97_d.R

Initial commit for doi.org/10.25502/hwdb-p578 in carob/scripts/variety_performance

---

scripts/fertilizer/doi_10.21421_D2_01WXFG.R
scripts/fertilizer/doi_10.21421_D2_5093XX.R
scripts/fertilizer/doi_10.21421_D2_EYFR2F.R
scripts/fertilizer/doi_10.21421_D2_STACVA.R
scripts/fertilizer/doi_10.21421_D2_YAJKSE.R
scripts/fertilizer/doi_10.21421_D2_YDFJOB.R

6 additional nut-fert data ses

6 additional nut-fert data ses

---

scripts/variety_performance/doi_10.25502_14m8-cs44_d.R
scripts/variety_performance/doi_10.25502_6G5B-RM44_D.R
scripts/variety_performance/doi_10.25502_NY1Z-W564_D.R

…ing fertilizer amounts to scripts/variety_performance/doi_10.25502_6G5B-RM44_D.R

adding scripts/variety_performance/doi_10.25502_NY1Z-W564_D.R and adding fertilizer amounts to scripts/variety_performance/doi_10.25502_6G5B-RM44_D.R

---

scripts/soil_information/doi_10.25502_20180814_1355_HJ.R
scripts/soil_information/doi_10.25502_20180814_1504_HJ.R

I Added two new dataset in soil information group.
while  waiting for the decision of keeping the new group or bring back the data to fertilizer group since these data contain also fertilizer information.  Thank you

New dataset Added 

---

scripts/_pending/doi_10.25502_JHRJ-9423.R
terms/fertilizers.csv

@rhijmans @smkuhlani @egbendito @mukami3juma @cedricngakou  I have corrected the data set  doi_10.25502_JHRJ-9423, This seemed to be a groundnut experiment since only the groundnut records have fertilizer and variety information. Also I would like to ask if there was a better way of doing the joins I resorted to just do a carobiner::bindr as a left join resulted to very many entries in the end.
I also added gypsum to the list of fertilizers

Pending dataset review and addition to the fertilizer csv

---

scripts/fertilizer/doi_org_10.25502_RGB5_GA15_D.R

New dataset added in fertilizer group

New dataset (https://doi.org/10.25502/RGB5-GA15/D) for fertilizer group

---

references/doi_10.1016_j.fcr.2022.108578.ris
scripts/fertilizer/doi_10.5061_dryad.j3tx95xhc.R

First dataset for Dryad, please review.
Also, it is an aggregated dataset, both from literature and other datasets, thus `dset$experiment_type <- "meta-analysis"`, but please confirm.

Add fertilizer/doi_10.5061_dryad.j3tx95xhc.R

---

scripts/fertilizer/doi_10.25502_20180814_1154_HJ.R

I had fixed the start_date on doi:10.25502/20180814/1154/HJ

start_date fixed

---

scripts/fertilizer/doi_10.25502_20180814_0923_HJ.R
scripts/fertilizer/doi_10.25502_PAKR-Y904_D.R

This dataset is from AFSIS but more complete than what is include in  doi_10.7910_DVN_UNLRGC. Please have a look

New dataset (https://doi.org/10.25502/20180814/0923/HJ).

---

scripts/fertilizer/doi_10.25502_20180814_0923_HJ.R

fertilizer_type fixed on doi.org/10.25502/20180814/0923/HJ

fertilizer_type fixed

---

scripts/wheat_yield/hdl_11529_10825.R

This is a new dataset (hdl_11529_10825)  I assign it to crop_cuts Group  but i'm not sure please have a look.

New dataset (https://hdl.handle.net/11529/10825)

---

scripts/wheat_yield/hdl_11529_10548227.R
scripts/wheat_yield/hdl_11529_10548247.R
scripts/wheat_yield/hdl_11529_10548587.R

second tranche updates

---

scripts/wheat_yield/hdl_11529_10831.R

New dataset from  CIMMYT (hdl.handle.net/11529/10831). Please have a look

New dataset(hdl.handle.net/11529/10831)

---

scripts/fertilizer/doi_10.25502_V1CA-7Y60.R
scripts/fertilizer/doi_10.7910_DVN_H23MVL.R

This is a new dataset from N2Africa

New dataset(doi.org/10.25502/V1CA-7Y60)

---

terms/crops.csv

I added the upper boundary of yield per crop please have a look. Thank  you

upper boundary of yield range per crop added

---

scripts/fertilizer/doi_10.7910_DVN_LTS278.R

Commented out RH's message and treatment example.
Added lon & lat values for the 2 locations.

Added N & P values for treatment A (Ctrl/FP) & B (Cal. P & rec. N).

---

scripts/fertilizer/doi_10.25502_HNKM-Y645_D.R

nodule weight should be added to the records.csv

first entry of doi_10.25502_HNKM-Y645_D

---

scripts/fertilizer/doi_10.25502:ac6r-kx93.R
scripts/wheat_trials/hdl_11529_11089.R

added two datasets:
1. scripts/fertilizer/doi_10.25502:ac6r-kx93.R
2. scripts/wheat_trials/hdl_11529_11089.R

added two new datasets for fertilizer and wheat

---

scripts/fertilizer/doi_10.25502-EZQV-ZZ19.R

Additional new dataset for Nigeria

added Nigeria dataset

---

scripts/fertilizer/doi_org_10_25502_8YQ1-DM57_D.R

Potential issues on the p_fertilizer, yield and biomass values. This might need a revision once Joost provides a response.

Potential issues on the p_fertilizer, yield and biomass values. 

---

scripts/_pending/doi_org_10_25502_8YQ1-DM57_D.R

since it was repeated from fertilizer/doi_10.25502_8yq1-dm57_d.R

move #147 to _pending/doi_10.25502_8YQ1-DM57_D.R

---

scripts/fertilizer/doi_10.25502_gzyt-ks92.R

This is a new dataset from N2Africa but yield is expressed in Kg not in kg/ha , please have a look. Thanks

New dataset (doi:10.25502/gzyt-ks92)

---

scripts/_pending/doi_10.25502_6h5e-q472.R
scripts/fertilizer/doi_10.25502_6h5e-q472.R

Kindly revise my contribution 
Thanks

Revision request of: doi_10.25502_6h5e-q472.R 

---

scripts/fertilizer/doi_10.25502_Y18Z-6T60.R
scripts/fertilizer/doi_10.25502_rhfq-vk94.R

New dataset from N2Africa please have a look. Thanks

New dataset (doi:10.25502/Y18Z-6T60)

---

scripts/fertilizer/doi_10.25502_K1TM-5012.R

This is a new dataset from N2Africa, please have a look. Thanks

New dataset (doi:10.25502/K1TM-5012)

---

scripts/maize_trials/hdl_11529_2223085.R

Created new script for maize trials.

New Standadized dataset

---

scripts/fertilizer/doi_10.25502_P8EQ-C814_D.R
scripts/fertilizer/doi_10.25502_wpce-te77_d.R
scripts/fertilizer/doi_10.25502_ysjw-cw72.R

New dataset from N2africa ( doi:10.25502/ysjw-cw72),  please have a look. Thanks

New dataset (doi:10.25502/ysjw-cw72)

---

scripts/_pending/doi_10.7910_DVN_FPPDCG.R
scripts/_pending/doi_10_7910_DVN_GVNJAB.R
scripts/_pending/hdl_11529_10548646.R
terms/groups.csv
terms/records.csv

New PR. Resolve requirement for soil data to have crop name, yield and yield_part. These may not be applicable here.

new soil datasets commit

---

scripts/wheat_trials/hdl_11529_10548246.R

May you kindly review the standardised dataset for wheat trials

Standardised data for wheat trials

---

scripts/potato_trials/doi_10.21223_P3_UTZBYL.R

I've added soil information, but I've noticed that most files contain NA value in soil analysis sheet.

Soil data added

---

scripts/conservation_agriculture/hdl_11529_10547997.R

May you kindly review the standardised script. Also advise the group to put since the uri has datasets with different crops.

standardized script

---

scripts/fertilizer/doi_10.21223_R5CN7B.R

@Hopafela please check your script and see the change. Thanks

New dataset (doi:10.21223/R5CN7B)

---

scripts/conservation_agriculture/hdl_11529_10548008.R

Please kindly review the standardised datasets

new datasets

---

scripts/wheat_trials/hdl_11529_10989.R

Elite selection Wheat trial

---

scripts/conservation_agriculture/hdl_11529_10548582.R

Kindly review and advise on the standardised dataset

Standardised script as group during workshop; adding new dataset hdl_11529_10548582.R

---

git token/git token
scripts/wheat_trials/hdl_11529_10548615.R

May you please review my wheat dataset and kindly share the feedback

commit of dataset 11529_10548615

---

scripts/conservation_agriculture/doi_10.7910_DVN_QLJUY7.R
scripts/conservation_agriculture/hdl_11529_10548076.R

May you kindly check my standardised data set.

New standardised set doi_10.7910_DVN_QLJUY7

---

scripts/wheat_trials/hdl_11529_10548035.R

Complements of the season. May you review my script and provide feedback.

Commit of wheat dataset hdl_11529_10548035.

---

scripts/conservation_agriculture/doi_10.7910_DVN_NZW56Q.R

Dataset was for an on-farm trial done in Malawi (2018) to compare effects of conservation agricultural technologies.

New dataset doi_10.7910_DVN_NZW56Q

---

scripts/maize_trials/doi_10.25502_SZWF-HE08.R

"New'  maize trial data set

---

scripts/conservation_agriculture/doi_10.7910_DVN_NZW56Q.R

Additions on N_fertilizer application rate and genotype names for cowpea and pigeon pea.

N_fertilizer application rate additions

---

scripts/fertilizer/doi_10.21223_YACJGV.R

The yields were in t/ha but upon conversion the yield bounds were too high. There is a possibility of wrong entry.

First entry from Mary and Stephen

---

scripts/maize_trials/hdl_11529_10667.R

Data set is for individual trial results from the International Late Yellow Hybrid  
(Mid-altitude / Subtropical Three Way Crosses Yellow Hybrids, with High Concentrations of Provitamins A 
(especially beta-carotene) - CHTSPROA) conducted in 2012.

New dataset hdl_11529_10667 (maize_trial)

---

scripts/wheat_trials/hdl_11529_10999.R

kindly review and merge script hdl:11529/10999

request for merge of script hdl:11529/10999

---

scripts/wheat_trials/hdl_11529_10786.R
scripts/wheat_trials/hdl_11529_10788.R

kindly review script hdl:11529/10788

commit of wheat script hdl:11529/10788

---

scripts/wheat_trials/hdl_11529_10790.R

commit of wheat script hdl:11529/10790

---

scripts/fertilizer/hdl_11529_11012.R

There seems to be a problem with the identifier. Kindly advise.

Commit of fertilizer script hdl:11529/11012

---

scripts/wheat_trials/hdl_11529_10548522.R

kindly review script hdl_11529_10548522

commit of script hdl_11529_10548522

---

doi_10.7910_DVN_1T4Q3F.R

some changes made to the file doi:10.7910/DVN/1T4Q3F
please consider the changes to the latest script

 doi:10.7910/DVN/1T4Q3F please consider  the latest script

---

scripts/soil_samples/doi_10.18167_DVN1_VPOCHN.R

This is the correct version of this particular dataset. The one we sent before may now be removed from pending.

commmit of updated script doi:10.18167/DVN1/VPOCHN

---

doi_10.7910_DVN_EQZR5C.R

some changes made to the dataset doi_10.7910_DVN_EQZR5C

 doi_10.7910_DVN_EQZR5C

---

doi_10.21223_P3_OTYRIV.R

Kindly review the code uploaded.

doi:10.21223/P3/OTYRIV

---

hdl_11529_10548976.R

some changes made to the file hdl_11529_10548976

 hdl_11529_10548976

---

hdl_11529_11016.R

some changes made to the file hdl_11529_11016

 hdl_11529_11016

---

scripts/conservation_agriculture/hdl_11529_10868.R

commit of wheat script hdl:11529/10868

---

doi_10.7910_DVN_LSDQ5C.R

previous_crop contains invalid term "pasture"

some changes made to the script doi:10.7910_DVN_LSDQ5C

---

scripts/wheat_trials/doi_10.18167_DVN1_KKMZAD.R

new script : doi_10.18167_DVN1_KKMZAD.R

---

scripts/conservation_agriculture/hdl_11529_10842.R

kindly review script hdl:11529/10842

commit of CA dataset hdl:11529/10842

---

scripts/wheat_trials/hdl_11529_10548531.R

kindly review wheat script hdl:11529/10548531

commit of wheat script hdl:11529/10548531

---

scripts/wheat_trials/hdl_11529_10548591.R

kindly review script hdl 11529 10548591

commit of wheat script hdl 11529 10548591

---

scripts/wheat_trials/hdl_11529_10548277.R

kindly review script hdl:11529/10548277

commit of wheat dataset hdl:11529/10548277

---

scripts/wheat_trials/hdl_11529_10804.R

commit of wheat script hdl_11529_10804

---

scripts/conservation_agriculture/doi_10.18167_DVN1_VPOCHN.R
scripts/conservation_agriculture/hdl_11529_10548829.R
terms/variables_soil.csv

Added the script for processing doi:10.7910/DVN/8JMMUZ dataset

---

scripts/wheat_trials/hdl_11529_10806.R

kindly review script hdl:11529/10806

commit of wheat script hdl:11529/10806

---

scripts/soil_samples/doi_10.7910_DVN_1YZAQZ.R
scripts/soil_samples/doi_10.7910_DVN_CQLR9B.R

Adding the following:
1. doi:10.7910/DVN/1YZAQZ
2. doi:10.7910/DVN/CQLR9B

Adding two new datasets.

---

references/hdl_11529_10548972.ris
scripts/conservation_agriculture/hdl_11529_10548972.R

conservation agriculture dataset hdl:11529/10548972

---

scripts/conservation_agriculture/hdl_11529_10548578.R

commit of coservation agriculture acript hdl:11529/10548578

---

scripts/wheat_trials/hdl_11529_10810.R

commit of wheat script hdl:11529/10810

---

hdl_11529_10548239.R

standardised script hdl:11529/10548239

changes made to the script hdl:11529/10548239

---

hdl_11529_10548312.R

changes made to the file hdl:11529/10548312

changes made to the script hdl:11529/10548312

---

scripts/soil_samples/doi_10.34725_DVN_CBHCKS.R
scripts/soil_samples/doi_10.7910_DVN_28944.R

Please review my PR for this new dataset.

CAARPE project dataset

---

scripts/crop_cuts/hdl_11529_10548214.R

a new script "hdl:11529/10548214"

new script "hdl:11529/10548214"

---

hdl_11529_10548245.R

new script hdl:11529/10548245

---

references/doi.org_10.1016_j.agee.2021.107812.ris
scripts/conservation_agriculture/hdl_11529_10548832.R

commit of CA dataset hdl/11529/10548832

---

scripts/wheat_trials/hdl_11529_10548394.R

commit of wheat script hdl:11529/10548394

---

scripts/wheat_trials/hdl_11529_10548398.R

commit of wheat script hdl:11529/10548398

---

scripts/wheat_trials/hdl_11529_10548396.R

commit of wheat script hdl:11529/10548396

---

hdl_11529_10548593.R

please review script hdl:11529/10548593

 hdl:11529/10548593

---

scripts/wheat_trials/hdl_11529_10548811.R

kindly review the last committed script and discard the first 2.

commit of wheat script hdl:11529/10548811

---

references/doi_10.1017_S1742170521000442.ris
scripts/conservation_agriculture/hdl_11529_10548835.R

commit of CA script hdl:11529/10548835

---

scripts/hdl_11529_221663.R

please review new script hdl:11529/221663

 hdl_11529_221663

---

scripts/wheat_trials/hdl_11529_10548401.R

commit of wheat script hdl:11529/10548401

---

scripts/varieties_wheat/hdl_11529_10548047.R

Standardised dataset hdl_11529_10548047.R

Standardised dataset hdl_11529_10548047.R

---

scripts/hdl_11529_10548568.R

please review new script hdl:11529/10548568

new script hdl:11529/10548568

---

scripts/agronomy/hdl_11529_10548681.R

commit of script hdl:11529/10548681

---

scripts/_pending/agronomy/hdl_11529_10548568.R

please review revised script hdl:11529/10548568

please find revised script hdl:11529/10548568

---

scripts/_pending/conservation_agriculture/hdl_11529_10843.R

Consider this data set in pending/conservation_agriculture, for transfer to the scripts/agronomy.
FYA:
1-Added 2 additional data sheets which were not initially processed. 2-As a result, almost everything has been changed from the initially submitted data set. 3-The 3rd data sheet (HRS sunn hemp yield), does not have grain yield, but only biomass. It is therefore not clear whether we should have it or not. As of now i have removed those rows with no yield. May you please advise.

Revised a data set in the pending folder.

---

scripts/_pending/conservation_agriculture/doi_10.7910_DVN_FVEISH.R
scripts/_pending/conservation_agriculture/hdl_11529_10843.R

Revised script in pending, for consideration to transfer to scripts/a…
1- Residue_prevcrop, is challenging because there is no explicit mention of how much residues were carried over. You only assume based on the previous biomass. According to literature they evenly spread the residues in the plot https://acsess.onlinelibrary.wiley.com/doi/abs/10.2135/cropsci2014.11.0796 In some cases the number of plots change from 20 to 25, in the next year. It therefore becomes unclear, what residues was applied and where they came from. Maybe they get them from outside the field.
2-It is not clear, if ether grain or biomass are expressed in fresh weight or dry weight. Based on the paper above they dry them and then reweighed. So i assumed its dry weight.

Revised script in pending

---

scripts/soil_samples/doi_10.7910_DVN_XZIRK0.R
scripts/soil_samples/hdl_11529_10548238.R

Thanks Robert. Done as advised. Regards

"Adding new dataset doi_10.7910_DVN_XZIRK0.R

---

scripts/hdl_11529_10549071.R

new script hdl:11529/10549071 
There is no description of the Treatment just numbers

new script hdl:11529/10549071

---

misc/todo/to-do.csv

Added 10 new data sets for potential processing.

Added 10 new data sets for potential processing.

---

misc/todo/to-do.csv

Added 11 more data sets to the to do list for potential processing.

Added 11 more data sets to the to do list for potential processing.

---

misc/todo/to-do.csv

Revert "Added 11 more data sets to the to do list for potential processing."

---

scripts/_pending/conservation_agriculture/doi_10.7910_DVN_1T4Q3F.R

Consider moving to agronomy/scripts:
1-Treatment column originally specified to a column with treatment codes. re-assigned treatment to a column with treatment description. 2-Communicated with data authors to know fertilizer information, which was missing initially. 3-Data set appears to be missing some treatments e.g. maize-maize, instead it only shows groundnut-maize treatments.

Processed data set in pending

---

scripts/hdl_11529_10548773.R

please review new script hdl:11529/10548773

new script hdl:11529/10548773

---

scripts/varieties/doi_10.21421_D2_GZ0L5Q.R

@rhijmans I added the rust disease score recorded at different date after planting as timerecs  please check. Thanks

New dataset (doi:10.21421/D2/GZ0L5Q)

---

scripts/agronomy/hdl_11529_10548624.R

commit of agronomy script hdl:11529/10548624

---

references/doi_10.1017_S0021859614000525.ris
scripts/agronomy/doi_10.21421_D2_NCNXL8.R

commit of agronomy data doi.org/10.1017S0021859614000525

---

scripts/agronomy/hdl_11529_10548651.R

commit of agronomy script hdl:11529/10548651

---

scripts/varieties/doi_10.21223_P3_NQBNWX.R
scripts/varieties/doi_10.21223_WRPMJI.R

Adding a dataset doi_10.21223_P3_NQBNWX

---

references/doi_10.1007_s10705-018-9912.ris
scripts/_pending/agronomy/doi_10.5061_dryad.3692hh9.R

adding reference for publication

review of doi_10.5061_dryad.3692hh9.R

---

scripts/hdl_11529_10548393.R

please review new script hdl:11529/10548393

new script hdl:11529/10548393

---

scripts/agronomy/hdl_11529_10547963.R

@rhijmans this script take some time to run over. It is due to the number of files in the raw dataset .
is it possible to subset it into multiple files ( 3 or 4) to reduce the running time script?

New dataset (hdl:11529/10547963)

---

scripts/varieties/hdl_11529_10548650.R

Commit of variety script hdl:11529/10548650

---

scripts/hdl_11529_10548945.R

please review new script hdl:11529/10548945

hdl:11529/10548945

---

scripts/varieties/doi_10.21223_P3_1GET14.R
scripts/varieties/doi_10.21223_P3_BOXOEZ.R
scripts/varieties/doi_10.21223_P3_H50YAO.R
scripts/varieties/doi_10.21223_P3_M40FYT.R
scripts/varieties/doi_10.21223_P3_MWOJGR.R
scripts/varieties/doi_10.21223_P3_OOQ73N.R
scripts/varieties/doi_10.21223_P3_SFXXDC.R
scripts/varieties/doi_10.21223_P3_UGWAZL.R
scripts/varieties/doi_10.21223_P3_VYCLVX.R

Hi Robert & Eduardo
I'm adding these 9 carob scripts for potato varieties.

Request to: Add 9 carob scripts for varieties.

---

scripts/hdl_11529_10548722.R

Please review new script hdl:11529/10548722

hdl:11529/10548722

---

scripts/pest_disease/_functions.R

Additional processing function for `pest_disease` `group` based on datasets proposed in #511
@rhijmans @henryjuarez @cedricngakou

New processing funcion for late blight datasets in #511

---

scripts/_pending/conservation_agriculture/hdl_11529_10548767.R

Revised data set (hdl_11529_10548767.R) in pending folder. Assess and consider moving to scripts/agronomy
Specifically:
1-Added additional variables such as irrigation and related details.
2-Added more data which was in another sheet.

Revised data set in pending folder

---

scripts/varieties_wheat/hdl_11529_10548695.R

May you kindly test the standardised dataset, Its giving some errors when i testing the scripts.

Standardised data Set hdl_11529_10548695.R

---

scripts/agronomy/hdl_11529_10548518.R

commit of agronomy script hdl:11529/10548518

---

scripts/agronomy/doi_10.21421_D2_TVF4M5.R

@rhijmans This data can probably be move to pending as there is a need of protocol to clarify the treatment, please take a look. Thanks

New dataset (doi:10.21421/D2/TVF4M5)

---

scripts/hdl_11529_10542.R

please review new script hdl:11529/10542

 script hdl:11529/10542

---

references/doi_10.21273_HORTSCI.51.5.597.ris
scripts/_pending/varieties/doi_10.21223_P3_DP0OYK.R

New dataset (doi:10.21223/P3/DP0OYK)

---

scripts/hdl_11529_10544.R
scripts/hdl_11529_10547.R

Please review new script hdl:11529/10544

Please review new script hdl:11529/10544

---

scripts/hdl_11529_10534.R

please review new script hdl_11529_10534

---

scripts/hdl_11529_10562.R

please review new script hdl:11529/10562

New script hdl:11529/10562

---

scripts/_pending/agronomy/doi_10.25502_K1TM-5012.R

Checek if ( _pending/agronomy/doi_10.25502_K1TM-5012.R) is ready to move to scripts/agronomy
Complex data set.
1-Added planting date. Though not sure if this is OK for survey data. In this case we used the survey dates as planting date. 
2-Added intercrops. Also an issue columns with 2 crops one was assumed to be the intercrop. 
3-Removed rows where crop yield was NA.
4-Removed duplicates, though am not comforbale with this idea. A duplicate might simply be households nearer to each other with simuilar farming systems and productivty.

Checek if ready to move to scripts/agronomy

---

scripts/varieties/doi_10.21223_P3_3WAPNU.R
scripts/varieties/doi_10.21223_P3_CDCKNH.R
scripts/varieties/doi_10.21223_P3_CINPSO.R
scripts/varieties/doi_10.21223_P3_KATPZ8.R
scripts/varieties/doi_10.21223_P3_LDMFOM.R
scripts/varieties/doi_10.21223_P3_MO4PSJ.R
scripts/varieties/doi_10.21223_P3_XGKXGE.R
scripts/varieties/doi_10.21223_P3_YWXFWM.R

This group of Datasets are very similar.

Similar Datasets

---

scripts/hdl_11529_11154.R

Please review new script hdl:11529/11154

Please review new script hdl:11529/11154

---

scripts/_pending/varieties_potato/doi_10.21223_NZUS1C.R
scripts/_pending/varieties_potato/doi_10.21223_OOQ16Y.R

Robert, here are the 2 Scripts from "pending" more streamlined.

Updated scripts for doi_10.21223_NZUS1C & doi_10.21223_OOQ16Y

---

scripts/varieties_potato/doi_10.21223_P1ZLI7.R
scripts/varieties_potato/doi_10.21223_XPF4C8.R

doi_10.21223_P1ZLI7 & doi_10.21223_XPF4C8

---

scripts/_pending/varieties_potato/doi_10.21223_L9WDYD.R
scripts/_pending/varieties_potato/doi_10.21223_WCLRKI.R

Hi Robert
Both scripts has been updated for proper column handling, location georeferencing & consistent naming of the data frame (d)

doi_10.21223_L9WDYD & doi_10.21223_WCLRKI from pendings

---

scripts/varieties_potato/doi_10.21223_7WC7FM.R

R.
rAUDPC in the original dataset is out of bonds. (70, 2397.5)
I suggest to re-calculate this column in the original dataset. 
Let mw know how to manage this.

doi:10.21223/7WC7FM

---

scripts/agronomy/hdl_11529_11014.R

The raw data indicate that the trial covered Oromia and Amhara regions, including Jimma, Wollega, West Showa, East Showa, and Gojjam districts. However, the specific data collection locations were not identified. I have contacted the authors to request this information and also the information on fertilizer types and NPK amounts.

New dataset - hdl:11529/11014

---

scripts/varieties_maize/hdl_11529_10549157.R

kindly review the maize script hdl:11529/10549157

commit of maize script hdl:11529/10549157

---

scripts/varieties/doi_10.21421_D2_LIY0MP.R

Hi @cedricngakou; please review this

New dataset

---

scripts/soil_samples/doi_10.71682_10549328.R

kindly review soil script doi:10.71682/10549328

commit of soil script doi:10.71682/10549328

---

scripts/soil_samples/doi_10.71682_10549329.R

review soil script doi:10.71682/10549329

commit of soil script doi:10.71682/10549329

---

scripts/soil_samples/hdl_11529_10549136.R

review soil script hdl:11529/10549136

commit of soil soil script hdl:11529/10549136

---

scripts/varieties_wheat/hdl_11529_10548150.R

review soil script hdl:11529/10548150

Commit of soil script hdl:11529/10548150

---

scripts/soil_samples/hdl_11529_10548809.R

review the revised soil script hdl:11529/10548809

commit of revised soil soil script hdl:11529/10548809

---

scripts/soil_samples/hdl_11529_10548809.R

review modified script with soil_P_method for individual extraction methods hdl:11529/10548809

modified script with soil_P_method for individual extraction methods hdl:11529/10548809

---

scripts/soil_samples/hdl_11529_10548743.R

review soil script hdl:11529/10548743

commit of soil script hdl:11529/10548743

---

scripts/soil_samples/hdl_11529_10548743.R

corrected soil script hdl:11529/10548743

---

scripts/survey/doi_10.7910_DVN_ILVSXJ.R

I was obliged to use library(haven) in the script to read files with the ".dta" extension. Could we integrate this extension into the carobiner function?

New dataset (doi:10.7910/DVN/ILVSXJ)
